<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxizy4x\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxizy4x/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRxizy4x.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRxizy4x\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRxizy4x\appProdProjectContainer([
    'container.build_hash' => 'Rxizy4x',
    'container.build_id' => '9b6acade',
    'container.build_time' => 1641487655,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxizy4x');
