<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTlxmckx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTlxmckx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTlxmckx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTlxmckx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTlxmckx\appProdProjectContainer([
    'container.build_hash' => 'Tlxmckx',
    'container.build_id' => '45d2cef5',
    'container.build_time' => 1634978128,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTlxmckx');
