<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5qiashf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5qiashf/appProdProjectContainer.php') {
    touch(__DIR__.'/Container5qiashf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container5qiashf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container5qiashf\appProdProjectContainer([
    'container.build_hash' => '5qiashf',
    'container.build_id' => 'e1acf908',
    'container.build_time' => 1634977597,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5qiashf');
