<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUzjilxd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUzjilxd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUzjilxd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUzjilxd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUzjilxd\appProdProjectContainer([
    'container.build_hash' => 'Uzjilxd',
    'container.build_id' => '1310978d',
    'container.build_time' => 1641487652,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUzjilxd');
